#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 8.0
#  in conjunction with Tcl version 8.6
#    May 10, 2026 08:38:59 PM BST  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *

import ytmstv2

_debug = True # False to eliminate debug printing from callback functions.

def main(*args):
    '''Main entry point for the application.'''
    global root
    root = tk.Tk()
    root.protocol( 'WM_DELETE_WINDOW' , root.destroy)
    # Creates a toplevel widget.
    global _top1, _w1
    _top1 = root
    _w1 = ytmstv2.MainWindow(_top1)
    # Creates a toplevel widget.
    global _top2, _w2
    _top2 = tk.Toplevel(root)
    _w2 = ytmstv2.AdvancedSettings(_top2)
    root.mainloop()

def advOptions(*args):
    if _debug:
        print('ytmstv2_support.advOptions')
        for arg in args:
            print ('    another arg:', arg)
        sys.stdout.flush()

def saveAdvancedSettings(*args):
    if _debug:
        print('ytmstv2_support.saveAdvancedSettings')
        for arg in args:
            print ('    another arg:', arg)
        sys.stdout.flush()

def selectdir(*args):
    if _debug:
        print('ytmstv2_support.selectdir')
        for arg in args:
            print ('    another arg:', arg)
        sys.stdout.flush()

def sync(*args):
    if _debug:
        print('ytmstv2_support.sync')
        for arg in args:
            print ('    another arg:', arg)
        sys.stdout.flush()

def updatedir(*args):
    if _debug:
        print('ytmstv2_support.updatedir')
        for arg in args:
            print ('    another arg:', arg)
        sys.stdout.flush()
        return True

def updatelist(*args):
    if _debug:
        print('ytmstv2_support.updatelist')
        for arg in args:
            print ('    another arg:', arg)
        sys.stdout.flush()
        return True

if __name__ == '__main__':
    ytmstv2.start_up()




