#############################################################################
# Generated by PAGE version 8.0
#  in conjunction with Tcl version 8.6
#  May 10, 2026 09:50:46 PM BST  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    ::vTcl::MessageBox -title Error -message  "You must open project files from within PAGE."
    exit}


set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkTooltipFont
set vTcl(actual_gui_font_tooltip_name)  TkTooltipFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
########################################### 
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) gray40
set vTcl(analog_color_p) #c3c3c3
set vTcl(analog_color_m) beige
set vTcl(tabfg1) black
set vTcl(tabfg2) white
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
########################################### 
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) Absolute
set vTcl(mode) Absolute
set vTcl(project_theme) default



proc vTclWindow.top1 {base} {
    global vTcl
    if {$base == ""} {
        set base .top1
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu $top.m51 -background #d9d9d9 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 
    wm focusmodel $top passive
    wm geometry $top 489x110+729+434
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 3844 1061
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    set toptitle "ySync Music"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "MainWindow" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:copy_lock $top
    menu "$top.m51" \
        -activebackground #d9d9d9 -activeforeground black \
        -font "-family {Segoe UI} -size 9" -tearoff 0 
    ttk::button "$top.tBu50" \
        -command "selectdir" -text "Choose path" -width 97 -compound left \
        -cursor fleur 
    vTcl:DefineAlias "$top.tBu50" "FolderPickerButton" vTcl:WidgetProc "MainWindow" 1
    ttk::entry "$top.tEn49" \
        -exportselection 0 -font "-family {Segoe UI} -size 9" \
        -validate focusout -validatecommand "updatedir" -width 288 \
        -cursor fleur 
    vTcl:DefineAlias "$top.tEn49" "FolderPath" vTcl:WidgetProc "MainWindow" 1
    bind $top.tEn49 <<SetBalloon>> {
        set ::vTcl::balloon::%W {The path where the music will be outputted to}
    }
    ttk::button "$top.tBu47" \
        -command "advOptions" -text "Advanced" -compound left 
    vTcl:DefineAlias "$top.tBu47" "Advanced" vTcl:WidgetProc "MainWindow" 1
    ttk::button "$top.tBu51" \
        -command "sync" -text "Sync" -width 373 -compound none 
    vTcl:DefineAlias "$top.tBu51" "sBtn" vTcl:WidgetProc "MainWindow" 1
    ttk::label "$top.tLa49" \
        -background #d9d9d9 -font "-family {Segoe UI} -size 9" -relief flat \
        -text "Playlist URL:" -width 71 -compound left -cursor fleur 
    vTcl:DefineAlias "$top.tLa49" "PlaylistURLLabel" vTcl:WidgetProc "MainWindow" 1
    ttk::entry "$top.tEn50" \
        -exportselection 0 -font "-family {Segoe UI} -size 9" \
        -validate focusout -validatecommand "updatelist" -width 382 \
        -cursor fleur 
    vTcl:DefineAlias "$top.tEn50" "PlaylistURL" vTcl:WidgetProc "MainWindow" 1
    bind $top.tEn50 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Enter the URL to a YouTube or YouTube Music Playlist}
    }
    ttk::label "$top.tLa51" \
        -background #d9d9d9 -font "-family {Segoe UI} -size 9" -relief flat \
        -text "Output folder:" -width 82 -compound left 
    vTcl:DefineAlias "$top.tLa51" "FolderPathLabel" vTcl:WidgetProc "MainWindow" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.tBu50 \
        -in $top -x 382 -y 39 -width 97 -relwidth 0 -height 28 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tEn49 \
        -in $top -x 97 -y 39 -width 282 -relwidth 0 -height 28 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tBu47 \
        -in $top -x 382 -y 70 -width 97 -relwidth 0 -height 28 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tBu51 \
        -in $top -x 9 -y 70 -width 370 -relwidth 0 -height 28 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tLa49 \
        -in $top -x 10 -y 8 -width 87 -relwidth 0 -height 30 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tEn50 \
        -in $top -x 97 -y 7 -width 382 -relwidth 0 -height 28 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tLa51 \
        -in $top -x 10 -y 40 -width 82 -relwidth 0 -height 30 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

proc vTclWindow.top2 {base} {
    global vTcl
    if {$base == ""} {
        set base .top2
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background #d9d9d9 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 
    wm focusmodel $top passive
    wm geometry $top 212x89+861+444
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 3844 1061
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    set toptitle "Advanced Settings"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "AdvancedSettings" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    ttk::label "$top.tLa56" \
        -background #d9d9d9 -font "-family {Segoe UI} -size 9" -relief flat \
        -text "kbps" -compound left 
    vTcl:DefineAlias "$top.tLa56" "kb" vTcl:WidgetProc "AdvancedSettings" 1
    ttk::button "$top.tBu57" \
        -command "saveAdvancedSettings" -text "Save" -compound left 
    vTcl:DefineAlias "$top.tBu57" "savebtn" vTcl:WidgetProc "AdvancedSettings" 1
    ttk::label "$top.tLa52" \
        -background #d9d9d9 -font "-family {Segoe UI} -size 9" -relief flat \
        -text "Bit rate:" -compound left 
    vTcl:DefineAlias "$top.tLa52" "BitrateSelector" vTcl:WidgetProc "AdvancedSettings" 1
    ttk::label "$top.tLa50" \
        -background #d9d9d9 -font "-family {Segoe UI} -size 9" -relief flat \
        -text "Codec:" -compound left 
    vTcl:DefineAlias "$top.tLa50" "CodecSelector" vTcl:WidgetProc "AdvancedSettings" 1
    ttk::combobox "$top.tCo49" \
        -values "mp3 aac opus wmav2" -font "-family {Segoe UI} -size 9" \
        -textvariable "combobox" 
    vTcl:DefineAlias "$top.tCo49" "TCombobox1" vTcl:WidgetProc "AdvancedSettings" 1
    ttk::spinbox "$top.tSp54" \
        -from 1 -to 512 -font "-family {Segoe UI} -size 9" -background white 
    vTcl:DefineAlias "$top.tSp54" "TSpinbox1" vTcl:WidgetProc "AdvancedSettings" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.tLa56 \
        -in $top -x 0 -relx 0.656 -y 0 -rely 0.292 -width 0 -relwidth 0.269 \
        -height 0 -relheight 0.303 -anchor nw -bordermode ignore 
    place $top.tBu57 \
        -in $top -x 77 -y 55 -width 65 -relwidth 0 -height 26 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tLa52 \
        -in $top -x 0 -relx 0.047 -y 0 -rely 0.337 -width 0 -relwidth 0.245 \
        -height 0 -relheight 0.191 -anchor nw -bordermode ignore 
    place $top.tLa50 \
        -in $top -x 0 -relx 0.047 -y 0 -rely 0.112 -width 0 -relwidth 0.255 \
        -height 0 -relheight 0.191 -anchor nw -bordermode ignore 
    place $top.tCo49 \
        -in $top -x 0 -relx 0.283 -y 0 -rely 0.112 -width 0 -relwidth 0.646 \
        -height 0 -relheight 0.213 -anchor nw -bordermode ignore 
    place $top.tSp54 \
        -in $top -x 60 -y 30 -width 75 -relwidth 0 -height 20 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

proc 36 {args} {return 1}
proc updatedir {args} {return 1}
proc updatelist {args} {return 1}


Window show .
set btop1 ""
if {$vTcl(borrow)} {
    set btop1 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop1 $vTcl(tops)] != -1} {
        set btop1 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop1
Window show .top1 $btop1
if {$vTcl(borrow)} {
    $btop1 configure -background plum
}
set btop2 ""
if {$vTcl(borrow)} {
    set btop2 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop2 $vTcl(tops)] != -1} {
        set btop2 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop2
Window show .top2 $btop2
if {$vTcl(borrow)} {
    $btop2 configure -background plum
}

