#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 8.0
#  in conjunction with Tcl version 8.6
#    May 10, 2026 09:50:46 PM BST  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *
import os.path

_location = os.path.dirname(__file__)

import ytmstv2_support

_bgcolor = '#d9d9d9'
_fgcolor = '#000000'
_tabfg1 = 'black' 
_tabfg2 = 'white' 
_bgmode = 'light' 
_tabbg1 = '#d9d9d9' 
_tabbg2 = 'gray40' 

_style_code_ran = 0
def _style_code():
    global _style_code_ran
    if _style_code_ran: return        
    try: ytmstv2_support.root.tk.call('source',
                os.path.join(_location, 'themes', 'default.tcl'))
    except: pass
    style = ttk.Style()
    style.theme_use('default')
    style.configure('.', font = "TkDefaultFont")
    if sys.platform == "win32":
       style.theme_use('winnative')    
    _style_code_ran = 1

class MainWindow:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''

        top.geometry("489x110+729+434")
        top.minsize(120, 1)
        top.maxsize(3844, 1061)
        top.resizable(0,  0)
        top.title("ySync Music")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="#000000")

        self.top = top

        self.menubar = tk.Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)

        _style_code()
        self.FolderPickerButton = ttk.Button(self.top)
        self.FolderPickerButton.place(x=382, y=39, height=28, width=97)
        self.FolderPickerButton.configure(command=ytmstv2_support.selectdir)
        self.FolderPickerButton.configure(text='''Choose path''')
        self.FolderPickerButton.configure(compound='left')


        self.FolderPath = ttk.Entry(self.top)
        self.FolderPath.place(x=97, y=39, height=28, width=282)
        self.FolderPath.configure(exportselection="0")
        self.FolderPath.configure(font="-family {Segoe UI} -size 9")
        self.FolderPath.configure(validate="focusout")
        updatedir = self.FolderPath.register(ytmstv2_support.updatedir)
        self.FolderPath.configure(validatecommand=(updatedir))
        self.FolderPath_tooltip = \
        ToolTip(self.FolderPath, '''The path where the music will be outputted to''')

        self.Advanced = ttk.Button(self.top)
        self.Advanced.place(x=382, y=70, height=28, width=97)
        self.Advanced.configure(command=ytmstv2_support.advOptions)
        self.Advanced.configure(text='''Advanced''')
        self.Advanced.configure(compound='left')

        self.sBtn = ttk.Button(self.top)
        self.sBtn.place(x=9, y=70, height=28, width=370)
        self.sBtn.configure(command=ytmstv2_support.sync)
        self.sBtn.configure(text='''Sync''')
        self.sBtn.configure(compound='none')

        self.PlaylistURLLabel = ttk.Label(self.top)
        self.PlaylistURLLabel.place(x=10, y=8, height=30, width=87)
        self.PlaylistURLLabel.configure(background="#d9d9d9")
        self.PlaylistURLLabel.configure(font="-family {Segoe UI} -size 9")
        self.PlaylistURLLabel.configure(relief="flat")
        self.PlaylistURLLabel.configure(text='''Playlist URL:''')
        self.PlaylistURLLabel.configure(compound='left')

        self.PlaylistURL = ttk.Entry(self.top)
        self.PlaylistURL.place(x=97, y=7, height=28, width=382)
        self.PlaylistURL.configure(exportselection="0")
        self.PlaylistURL.configure(font="-family {Segoe UI} -size 9")
        self.PlaylistURL.configure(validate="focusout")
        updatelist = self.PlaylistURL.register(ytmstv2_support.updatelist)
        self.PlaylistURL.configure(validatecommand=(updatelist))
        self.PlaylistURL_tooltip = \
        ToolTip(self.PlaylistURL, '''Enter the URL to a YouTube or YouTube Music Playlist''')

        self.FolderPathLabel = ttk.Label(self.top)
        self.FolderPathLabel.place(x=10, y=40, height=30, width=82)
        self.FolderPathLabel.configure(background="#d9d9d9")
        self.FolderPathLabel.configure(font="-family {Segoe UI} -size 9")
        self.FolderPathLabel.configure(relief="flat")
        self.FolderPathLabel.configure(text='''Output folder:''')
        self.FolderPathLabel.configure(compound='left')

class AdvancedSettings:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''

        top.geometry("212x89+861+444")
        top.minsize(120, 1)
        top.maxsize(3844, 1061)
        top.resizable(0,  0)
        top.title("Advanced Settings")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="#000000")

        self.top = top
        self.combobox = tk.StringVar()

        _style_code()
        self.kb = ttk.Label(self.top)
        self.kb.place(x=139, y=26, height=27, width=57)
        self.kb.configure(background="#d9d9d9")
        self.kb.configure(font="-family {Segoe UI} -size 9")
        self.kb.configure(relief="flat")
        self.kb.configure(text='''kbps''')
        self.kb.configure(compound='left')

        self.savebtn = ttk.Button(self.top)
        self.savebtn.place(x=77, y=55, height=26, width=65)
        self.savebtn.configure(command=ytmstv2_support.saveAdvancedSettings)
        self.savebtn.configure(text='''Save''')
        self.savebtn.configure(compound='left')

        self.BitrateSelector = ttk.Label(self.top)
        self.BitrateSelector.place(x=10, y=30, height=17, width=52)
        self.BitrateSelector.configure(background="#d9d9d9")
        self.BitrateSelector.configure(font="-family {Segoe UI} -size 9")
        self.BitrateSelector.configure(relief="flat")
        self.BitrateSelector.configure(text='''Bit rate:''')
        self.BitrateSelector.configure(compound='left')

        self.CodecSelector = ttk.Label(self.top)
        self.CodecSelector.place(x=10, y=10, height=17, width=54)
        self.CodecSelector.configure(background="#d9d9d9")
        self.CodecSelector.configure(font="-family {Segoe UI} -size 9")
        self.CodecSelector.configure(relief="flat")
        self.CodecSelector.configure(text='''Codec:''')
        self.CodecSelector.configure(compound='left')

        self.TCombobox1 = ttk.Combobox(self.top)
        self.TCombobox1.place(x=60, y=10, height=19, width=137)
        self.value_list = ['mp3','aac','opus','wmav2',]
        self.TCombobox1.configure(values=self.value_list)
        self.TCombobox1.configure(font="-family {Segoe UI} -size 9")
        self.TCombobox1.configure(textvariable=self.combobox)

        self.TSpinbox1 = ttk.Spinbox(self.top, from_=1, to=512)
        self.TSpinbox1.place(x=60, y=30, height=20, width=75)
        self.TSpinbox1.configure(font="-family {Segoe UI} -size 9")
        self.TSpinbox1.configure(background="white")

from time import time, localtime, strftime
class ToolTip(tk.Toplevel):
    """ Provides a ToolTip widget for Tkinter. """
    def __init__(self, wdgt, msg=None, msgFunc=None, delay=0.5,
                 follow=True):
        self.wdgt = wdgt
        self.parent = self.wdgt.master
        tk.Toplevel.__init__(self, self.parent, bg='black', padx=1, pady=1)
        self.withdraw()
        self.overrideredirect(True)
        self.msgVar = tk.StringVar()
        if msg is None:
            self.msgVar.set('No message provided')
        else:
            self.msgVar.set(msg)
        self.msgFunc = msgFunc
        self.delay = delay
        self.follow = follow
        self.visible = 0
        self.lastMotion = 0
        self.msg = tk.Message(self, textvariable=self.msgVar, bg=_bgcolor,
                   fg=_fgcolor, font="TkTooltipFont",
                   aspect=1000)
        self.msg.grid()
        self.wdgt.bind('<Enter>', self.spawn, '+')
        self.wdgt.bind('<Leave>', self.hide, '+')
        self.wdgt.bind('<Motion>', self.move, '+')
    def spawn(self, event=None):
        self.visible = 1
        self.after(int(self.delay * 1000), self.show)
    def show(self):
        if self.visible == 1 and time() - self.lastMotion > self.delay:
            self.visible = 2
        if self.visible == 2:
            self.deiconify()
    def move(self, event):
        self.lastMotion = time()
        if self.follow is False:
            self.withdraw()
            self.visible = 1
        self.geometry('+%i+%i' % (event.x_root + 20, event.y_root - 10))
        try:
            self.msgVar.set(self.msgFunc())
        except:
            pass
        self.after(int(self.delay * 1000), self.show)
    def hide(self, event=None):
        self.visible = 0
        self.withdraw()
    def update(self, msg):
        self.msgVar.set(msg)
    def configure(self, **kwargs):
        backgroundset = False
        foregroundset = False
        # Get the current tooltip text just in case the user doesn't provide any.
        current_text = self.msgVar.get()
        # to clear the tooltip text, use the .update method
        if 'debug' in kwargs.keys():
            debug = kwargs.pop('debug', False)
            if debug:
                for key, value in kwargs.items():
                    print(f'key: {key} - value: {value}')
        if 'background' in kwargs.keys():
            background = kwargs.pop('background')
            backgroundset = True
        if 'bg' in kwargs.keys():
            background = kwargs.pop('bg')
            backgroundset = True
        if 'foreground' in kwargs.keys():
            foreground = kwargs.pop('foreground')
            foregroundset = True
        if 'fg' in kwargs.keys():
            foreground = kwargs.pop('fg')
            foregroundset = True

        fontd = kwargs.pop('font', None)
        if 'text' in kwargs.keys():
            text = kwargs.pop('text')
            if (text == '') or (text == "\n"):
                text = current_text
            else:
                self.msgVar.set(text)
        reliefd = kwargs.pop('relief', 'flat')
        justifyd = kwargs.pop('justify', 'left')
        padxd = kwargs.pop('padx', 1)
        padyd = kwargs.pop('pady', 1)
        borderwidthd = kwargs.pop('borderwidth', 2)
        wid = self.msg      # The message widget which is the actual tooltip
        if backgroundset:
            wid.config(bg=background)
        if foregroundset:
            wid.config(fg=foreground)
        wid.config(font=fontd)
        wid.config(borderwidth=borderwidthd)
        wid.config(relief=reliefd)
        wid.config(justify=justifyd)
        wid.config(padx=padxd)
        wid.config(pady=padyd)
#                   End of Class ToolTip

def start_up():
    ytmstv2_support.main()

if __name__ == '__main__':
    ytmstv2_support.main()




